
spring.application.name=codereview

server.port=8080

spring.data.mongodb.uri=mongodb://localhost:27017/codereviewdb

groq.api.key=${GROQ_API_KEY}
groq.api.url=https://api.groq.com/openai/v1/chat/completions
groq.model=openai/gpt-oss-120b